### ISSUE TITLE
WRong StatusString with FileOnDemand enabled in onedrive

### ISSUE THREAD

**Issue by srzelic** [rodneyviana/ODSyncService#3]
We got wrong StatusString with FileOnDemand enabled in onedrive. When we disable that option it works as expected.

**Comment by Calldor** [comment]
Same Problem Status with FileOnDemand is Show as "NotInstalled" but OneDrive is working

**Comment by rodgerzeisler** [comment]
I am having the same issue when using the File-on-Demand feature.  The StatusString is not reporting the correct status when FOD is enabled.  When I disabled, the StatusString that is reported is correct.

**Comment by robinmalik** [comment]
I came across this problem also, and noticed some odd results when troubleshooting the issue. Running Windows 10, 1809, Build 17763.253.

Results with 'Files on Demand' enabled for both a OneDrive Personal install, and OneDrive for Business install that is synchronising my own OneDrive and a shared SharePoint library. As we can see, only the SharePoint library shows as UpToDate.

```StatusString : UpToDate
LocalPath    : D:\My Company Name\PRJ0000000 - Project Title - Documents
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Business1

StatusString : NotInstalled
LocalPath    : D:\OneDrive - My Company Name
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Business1

StatusString : NotInstalled
LocalPath    : C:\Users\Me\OneDrive
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Personal```

Unticked files on demand for my PERSONAL OneDrive installation and checked the result again:

```StatusString : UpToDate
LocalPath    : D:\My Company Name\PRJ0000000 - Project Title - Documents
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Business1

StatusString : SharedSync
LocalPath    : D:\OneDrive - My Company Name
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Business1

StatusString : Syncing
LocalPath    : C:\Users\Me\OneDrive
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Personal```

What I find strange is that files on demand was only unticked for my personal OneDrive, and yet my business OneDrive had now changed to 'SharedSync'.

I then put the following into a 5 second loop: `do { Get-ODStatus ; start-sleep -seconds 5 } until($x -eq 1)`

After a minute or so, I got a more expected result:

```StatusString : UpToDate
LocalPath    : D:\My Company Name\PRJ0000000 - Project Title - Documents
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Business1

StatusString : NotInstalled
LocalPath    : D:\OneDrive - My Company Name
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Business1

StatusString : UpToDate
LocalPath    : C:\Users\Me\OneDrive
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Personal```

... so the business OneDrive showing as `NotInstalled` when files on demand is ticked.

I am hoping to prevent users from logging off whilst a sync is in progress, but files on demand is an essential part of the deployment so this issue is quite important if we're to use the .dll.

**Comment by reberrj** [comment]
Is there a resolution to the Files On Demand issue with this script?  I would really like to use this, but need to leave FoD on for the users while we run this.

**Comment by printzm** [comment]
I'd love to know what the resolution is too, as I want to use this, but we're using FOD as well.

**Comment by toffitomek** [comment]
Hi, same here, Files On Demand are used and we would love to hear how this tool deals with them...

**Comment by yatesa** [comment]
Yep I'm too now getting this StatusString NotInstalled.
Is this project abandoned, appears to be no update for two years?

**Comment by fuzzysb** [comment]
Not working for latest OD Client with Files on Demand. we need a method that works. any progress?

**Comment by yatesa** [comment]
Looking at the code it looks to me that it check for a particular icon status and if none match from the list then it returns NotInstalled. Well looking at the reg keys for FileSyncShell64.dll there are four other status types that exist but are not checked against: -

{1BF42E4C-4AF4-4CFD-A1A0-CF2960B8F63E} - UpToDateOverlay
{7AFDFDDB-F914-11E4-8377-6C3BE50D980C} - ErrorOverlay
{82CA8DE3-01AD-4CEA-9D75-BE4C51810A9E} - SyncingOverlay
{C5FF006E-2AE9-408C-B85B-2DFDD5449D9C} - UpToDateUnpinnedOverlay

Also in the ShellconOverlayIdentifiers reg key there are 7 for OneDrive, the code for this dll only checks for the first 6, the seventh one is {C5FF006E-2AE9-408C-B85B-2DFDD5449D9C}.

So my guess is that having Files On Demand enabled is making use of this new status, but the dll doesn't match against it, so it returns NotInstalled instead.

If had a clue how to update the code and recompile a new dll I would have a go. Anyone else know how to do it?

**Comment by rodneyviana** [comment]
Hi Yatesa,

I have a version that can test a particular overlay:
https://github.com/rodneyviana/ODSyncService/tree/master/DebugAndTraces

I ran this test on an On-Demand environment and no overlay seems to match. I am trying to get it figured out, but these are the GUIDs I tested to no avail:

Get-ODStatus -clsid '{BBACC218-34EA-4666-9D7A-C78F2274A524}' #  OneDrive1
Get-ODStatus -clsid '{5AB7172C-9C11-405C-8DD5-AF20F3606282}' #  OneDrive2
Get-ODStatus -clsid '{A78ED123-AB77-406B-9962-2A5D9D2F7F30}' #  OneDrive3
Get-ODStatus -clsid '{F241C880-6982-4CE5-8CF7-7085BA96DA5A}' #  OneDrive4
Get-ODStatus -clsid '{A0396A93-DC06-4AEF-BEE9-95FFCCAEF20E}' #  OneDrive5
Get-ODStatus -clsid '{9AA2F32D-362A-42D9-9328-24A483E2CCC3}' #  OneDrive6
Get-ODStatus -clsid '{C5FF006E-2AE9-408C-B85B-2DFDD5449D9C}' #  OneDrive7
Get-ODStatus -clsid '{8BA85C75-763B-4103-94EB-9470F12FE0F7}' #  SkyDrivePro1 (ErrorConflict)
Get-ODStatus -clsid '{CD55129A-B1A1-438E-A425-CEBC7DC684EE}' #  SkyDrivePro2 (SyncInProgress)
Get-ODStatus -clsid '{E768CD3B-BDDC-436D-9C13-E1B39CA257B1}' #  SkyDrivePro3 (InSync)
Get-ODStatus -clsid '{D9144DCD-E998-4ECA-AB6A-DCD83CCBA16D}' # EnhancedStorageShell
Get-ODStatus -clsid '{4E77131D-3629-431c-9818-C5679DC83E81}' # Offline Files


I got this by running this fromj PowerShell:
$regs = Get-ChildItem "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers"
$regs | % { Write-Host "Get-ODStatus -clsid '$($_.GetValue(''))' `# $($_.PSChildName)" }

As soon as I figure out, I will let you know.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rodneyviana** [comment]
I put together another version here: https://github.com/rodneyviana/ODSyncService/tree/master/Binaries/PowerShell

**Comment by yatesa** [comment]
Hi there, just tried the new dll. I now get: -
StatusString : OnDemandOrUnknown

I'm guessing you weren't able to specifically identify the OnDemand status then because even if I close OneDrive it still returns OnDemandOrUnknown.

Unfortunately that would not work for us either as we check the status to determine if OneDrive is active (and connected) before automatically adding a sync for Sharepoint site. If we continued on the basis that the status was OnDemandOrUnknown then that would fail if OneDrive wasn't actually active and connected.

I appreciate you trying to fix and understand you are completely limited by what the operating system/onedrive returns to you without a proper API. I was hoping that one of the other overlays would indicate the required status, but I guess not. Hopefully MS will sort out a proper API soon!

**Comment by rodneyviana** [comment]
I am working on the OnDemand workaround and will update the dll soon. It is already working with the version you have but it can be slow. I am on a client this week and will update it soon: either with a more efficient version or publishing the workaround

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fuzzysb** [comment]
@rodneyviana 

i was testing your update with files on demand. it works in english OS, but fails on spanish OS, just defaults to NotInstalled.

not sure if i'm missing something

**Comment by robinmalik** [comment]
Did some testing with the latest dll. Currently on Windows 10 1903 Build 18362.145). Files On Demand is enabled. These are the results for a synchronised SharePoint library (from an O365 group) and my individual OneDrive for Business.

Fully sychronised state:
```
StatusString : UpToDate
LocalPath    : D:\My Company Name\PRJ0000000 - Project Title - Documents
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Business1

StatusString : SharedSync
LocalPath    : D:\OneDrive - My Company Name
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Business1
```

Whilst writing data to disk, into my individual OneDrive for Business folder:
```
StatusString : OnDemandOrUnknown
LocalPath    : D:\My Company Name\PRJ0000000 - Project Title - Documents
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Business1

StatusString : OnDemandOrUnknown
LocalPath    : D:\OneDrive - My Company Name
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Business1
```

After writing to disk is complete, and whilst uploading:
```
StatusString : UpToDate
LocalPath    : D:\My Company Name\PRJ0000000 - Project Title - Documents
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Business1

StatusString : OnDemandOrUnknown
LocalPath    : D:\OneDrive - My Company Name
UserSID      : S-1-5-21-3459830550-2606870820-3563523489-1001
UserName     : COMPUTER\Me
ServiceType  : Business1
```

**Comment by yatesa** [comment]
> I am working on the OnDemand workaround and will update the dll soon. It is already working with the version you have but it can be slow. I am on a client this week and will update it soon: either with a more efficient version or publishing the workaround

Hi @rodneyviana, have you managed to get some time to update the dll with "more efficient version" as we still get "OnDemandOrUnknown" for most users. Or if not is it possible to publish the workaround?

**Comment by rodneyviana** [comment]
It is. I will try later this week.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rodneyviana** [comment]
Yatesa,

The last update version has a workaround for On Demand. I am still to write about it. For a large number of files it causes high CPU. So use it with care for now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by yatesa** [comment]
> Yatesa, The last update version has a workaround for On Demand. I am still to write about it. For a large number of files it causes high CPU. So use it with care for now. 

Thanks for update.

One thing I've noticed (since before applying this latest update), is that the status result is more often correct than it was previously. I'm not sure if this is related to your previous dll update or if its since Microsoft updated OneDrive (19.086.0502.0006 - where it shows the new style icon) but if I have On Demand enabled and nothing is actively syncing, then it shows the correct status.

However, I can still make it show OnDemandOrUnknown. The easiest way I can re-create the issue is by opening a csv file in my OneDrive as that seems to keep OneDrive in a syncing/Processing Changes state, with the cloud icon showing the circle and arrows overlaid. The new dll doesn't seem to change or improve this particular issue.

I need to do some more testing on other machines that had the issue to see what actually improves the status result, OneDrive update or new OneDrive status dll, but if we can get the correct status when OneDrive is running with On Demand but not actively syncing then that may be enough for us.

**Comment by fuzzysb** [comment]
I have this working in a different manor.  For files on demand when I get not installed as the result, I then view the status column wording on the top level folder. Not great languages but for English it works well

**Comment by sba923** [comment]
I always get "OnDemandOrUnknown" with the latest OneDrive client and Files-on-Demand enabled.

Both on home systems (consumer) and at work (ODFB).

Any plans to update the code to fix this?

(I _might_ find some time to look at it myself...)

**Comment by sharannishant** [comment]
I am running below error while running on Citrix VDA based on Server 2019 with FOD enabled.

Import-Module C:\TCS\ODTool\OneDriveLib.dll
Get-ODStatus
Get-ODStatus : Unable to find an entry point named '?GetShellInterfaceFromGuid@@YAJPEAHPEA_W1@Z' in DLL 'ODNative.dll'.
At line:1 char:1
+ Get-ODStatus
+ ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ODStatus], EntryPointNotFoundException
    + FullyQualifiedErrorId : System.EntryPointNotFoundException,OneDriveLib.GetStatus
